// Richard Kirchofer

// Even Fibonacci numbers
// Problem 2
// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms

#include <iostream>

using namespace std;

int main()
{
	int a, b, c, sum, counter;
	a = b = c = sum = counter = 0;
	b = 1;
	c = 1;

	while (c <= 4000000)
	{
		a = b + c;
		b = c + a;
		c = a + b;
		sum += a;
		counter ++;
	}
	cout << "sum is: " << sum << endl;
}

// (0) 1 1 (2) 3 5 (8) 13 21 (34) 55 89 (144) 233 
//	a 	b 	c
//	0 	1 	1
// 	1 	1 	1
// 	1 	2 	1
// 	1 	2 	(2)
// 	3 	4 	2
// 	3 	6 	(5)
// 	8 	6 	5
// 	8 	11 	5
// 	8 	11 	(13)
// 	
